spring.application.name=vaccination
server.port=8086

spring.config.import=optional:classpath:common-config.properties

# ── Discovery ─────────────────────────────────────────────────────────────
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1

# ── Services internes ──────────────────────────────────────────────────────
services.animaux.url=http://localhost:8083
services.organisation.url=http://localhost:8084
