package com.reseau_partage.core.entities.enumtypes;

public enum MotifMouvement {
    ACHAT, RETOUR_FOURNISSEUR, DON, PRODUCTION_INTERNE,
    UTILISATION_BANDE, UTILISATION_INDIVIDU, VACCINATION, TRAITEMENT,
    PERTE, VOL, PEREMPTION, DON_SORTIE,
    INVENTAIRE, CORRECTION, TRANSFERT
}