spring.application.name=auth
server.port=8081
server.address=0.0.0.0

# Import des configurations communes (DB, JWT, Upload) depuis le module core
spring.config.import=optional:classpath:common-config.properties

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

eureka.instance.prefer-ip-address=false
eureka.instance.hostname=localhost
eureka.instance.ip-address=127.0.0.1
