spring.application.name=auth
server.port=8081
server.address=0.0.0.0

# Import des configurations communes (DB, JWT, Upload) depuis le module core
spring.config.import=optional:classpath:common-config.properties

# ── Discovery ─────────────────────────────────────────────────────────────
eureka.client.service-url.defaultZone=http://192.168.1.190:8761/eureka

eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=192.168.1.190
