spring.application.name=auth
server.port=8081

# Import des configurations communes (DB, JWT, Upload) depuis le module core
spring.config.import=optional:classpath:common-config.properties

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
